name: black-checker

on: [push]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Black Code Formatter
        uses: psf/black@stable
        with:
          args: "-l 120 -t py38 --check ."
