name: black-checker

on: [push]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Black Code Formatter
        uses: psf/black@stable
        with:
          args: "--line-length 120 --target-version py38 --check ."
